name: update

on:
  push:
    branches: [main]
  schedule:
    - cron: "5 5 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd grouparoo && npm install
      - run: sudo npm install -g npm-check-updates
      - run: cd grouparoo && npm-check-updates -u
      - run: cd grouparoo && npm install
      - name: store-core-version
        run: echo CORE_VERSION=`cat grouparoo/package.json | jq -r '.dependencies."@grouparoo/core"'` >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with: 
          reviewers: ${{ secrets.BOT_PR_REVIEWER_USERS }}
          title: "Update to Grouparoo v${{ env.CORE_VERSION }}"
          body: "Grouparoo v${{ env.CORE_VERSION }} is now available."
          commit-message: "Updating Packages to v${{ env.CORE_VERSION }}"
          committer: Grouparoo Bot <hello@grouparoo.com>
          author: Grouparoo Bot <hello@grouparoo.com>
